'use strict';

const {
    binary: {
        Equals,
        Eq,
        StrictEquals,
        NotEquals,
        NotEq,
        StrictNotEquals,
        GreaterThan,
        GT,
        GreaterThanOrEqualTo,
        LessThan,
        LT,
        LessThanOrEqualTo,
        LTE,
        Modulus,
        Mod,
        Add,
        Concat,
        Subtract,
        Multiply,
        Divide
    },
    array: {
        Filter,
        Join,
        Every,
        Some,
        Find,
        Map,
        Sum,
        Product,
        FlatMap
    }
} = require('forast').trees;

const Operation = {
    '==': Equals,
    equals: Equals,
    eq: Equals,
    '===': StrictEquals,
    strictequals: StrictEquals,
    '!=': NotEquals,
    notequals: NotEquals,
    noteq: NotEquals,
    '!==': StrictNotEquals,
    strictnotequals: StrictNotEquals,
    '>': GreaterThan,
    greaterthan: GreaterThan,
    gt: GreaterThan,
    '>=': GreaterThanOrEqualTo,
    greaterthanorequalto: GreaterThanOrEqualTo,
    gte: GreaterThanOrEqualTo,
    '<': LessThan,
    lessthan: LessThan,
    lt: LessThan,
    '<=': LessThanOrEqualTo,
    lessthanorequalto: LessThanOrEqualTo,
    lte: LessThanOrEqualTo,
    '%': Modulus,
    modulus: Modulus,
    mod: Modulus,
    '+': Add,
    add: Add,
    concat: Concat,
    '-': Subtract,
    subtract: Subtract,
    '*': Multiply,
    multiply: Multiply,
    '/': Divide,
    divide: Divide,
    filter: Filter,
    join: Join,
    every: Every,
    some: Some,
    find: Find,
    map: Map,
    sum: Sum,
    product: Product,
    flatmap: FlatMap,
    template: require('./Template')
};

module.exports = Operation;
